---
title: "MMU R User Group"
---

<br>


The MMU R User Group exists to bring together R users of all levels, with interests in diverse fields from across the University to exchange tips, ideas and knowledge for the benefit of all.


See our general [aims and format]

[aims and format]: https://mmu-r-user-group.github.io/statement.html


**Check out our friends at RUM**
[RUM]: http://rumgroup.github.io/Home  


**Academic year 2016-17 Programme**

Sessions are held on the middle Wednesday of each month: 


| Topic           | Lead          | Date       | Place         | Time     |
| :-------------- |:--------------| :--------- | :-------------|:---------|
| Interactive Github tutorial   | Reka Solymosi (U of M)  | 12/10/2016 | BS 3.23 (Business School) |12.00 - 13.00 |
| Using R as a GIS              | Henry Partridge (MMU)   | 16/11/2016 |   E221 (John Dalton)      |12.00 - 13.00|
| Intro to ggplot2 / Q&A surgery| Ed Harris (MMU) / Surgery  |14/12/2016| BS 2.23 IT  (Business School) |12.00 - 13.00 |
|  Introduction to loops in R   | Christian Devenish      | 18/01/2017 | JD C1.02 (John Dalton)    |11.00 - 13.00|        
|  Connecting to databases (Traffic analysis) / Random Forests | Nick Gould / Ed Harris  | 15/02/2017| GM lab 120 (Geoffrey Manton) | 11.00 - 13.00|
|  Data manipulation in R (Open session) | All  | 15/03/2017| JD C 1.03 | 11.00 - 13.00 |
|  Easter break |   | 19/04/2017| | |
|  Using dply/tidyverse/pipes | Tom Higgenbottom | 17/05/2017| BS 3.08 | 12.00-14.00 |
|  Last session.... | | 21/06/2017| tbc | |



## Previous topics

* Interactive Github tutorial  
* [Using R as a GIS](https://github.com/rcatlord/tutorials/blob/master/GIS/GIS.md)  
* Intro to ggplot2  
* [Introduction to loops in R ](https://github.com/Cdevenish/Teaching/blob/master/IntroR/Intro_loops.r )  
* dply/tidyverse/pipes

