---
title: ""
output: 
  html_document
---

<br>

## MMUseR Group

<br>

#### Purpose

The MMU R User Group exists to bring together R users of all levels, with interests in diverse fields from across the University to exchange tips, ideas and knowledge for the benefit of all.

#### MMUseR Group Sessions 

Sessions are held on the middle Wednesday of each month. See [dates and programme]

[dates and programme]: https://mmu-r-user-group.github.io/index.html


#### Aims of the group

* to promote the R programming language across MMU
* to share knowledge of R
* to explore the use of R for a wide variety of purposes including statistical analysis, data science, GIS, reporting and others yet to be discovered
* to collaborate on problem solving using R
* to encourage reproducibility through the sharing of R code

#### Format

* R User Group meetings will be a mixture of presentations, drop-in surgeries and ad hoc training sessions
* The content of each meeting will be made up of contributions that have been volunteered by members of the group
* There will be a rotating chair so that the group is run and developed along cooperative lines

#### Outputs

* We will make all R User Group material available to members and the wider R community
* We will host a mini symposium each year to give members the opportunity to present their R outputs to the wider University

#### Modus operandi

* informal
* non-hierarchical - student and teaching / research staff will be treated as equals
* collaborative
* supportive
* welcoming to R users of all skill levels and those who are curious about the potential of R


#### R Consortium Code of Conduct

As a supported R User Group, we follow the R Consortium Code of Conduct, which of course, fits in with our aims:

A member of the R Community is:

##### Open:
Members of the community are open to collaboration, whether it's on projects, working groups, packages, problems, or otherwise. We're receptive to constructive comment and criticism, as the experiences and skill sets of other members contribute to the whole of our efforts. We're accepting of anyone who wishes to take part in our activities, fostering an environment where all can participate and everyone can make a difference.

##### Considerate:
Members of the community are considerate of their peers — other R users. We're thoughtful when addressing the efforts of others, keeping in mind that oftentimes the labor was completed simply for the good of the community. We're attentive in our communications, whether in person or online, and we're tactful when approaching differing views.

##### Respectful:
Members of the community are respectful. We're respectful of others, their positions, their skills, their commitments, and their efforts. We're respectful of the volunteer efforts that permeate the R community. We're respectful of the processes set forth in the community, and we work within them. When we disagree, we are courteous in raising our issues.

Overall, we're good to each other. We contribute to this community not because we have to, but because we want to. If we remember that, these guidelines will come naturally.

##### Questions/comments/reports?
Please write to the Code of Conduct address: conduct@r-consortium.org. (this will email the Board Chair and R Consortium Program manager). Include any available relevant information, including links to any publicly accessible material relating to the matter. 




